<a href="https://colab.research.google.com/github/jaswanth424/MachineLearning/blob/main/CarSalePrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from pandas.api.types import infer_dtype

In [40]:
df = pd.read_csv('/content/MAI101_Assignment1_used_vehicle_data.csv')

In [41]:
# check if df columns has mixed data types
mixed_cols = [col for col in df.columns if infer_dtype(df[col]).startswith("mixed")]
print("Columns with mixed types:", mixed_cols)

Columns with mixed types: []

In [42]:
display(df)

,MAKE,MODEL,YEAR,KILOMETRES,ENGINE_SIZE,FUEL_TYPE,TRANSMISSION,BODY_TYPE,DRIVETRAIN,DOORS,SEATS,ACCIDENTS,OWNERS,COLOUR,LISTING_DAYS,HAS_WARRANTY,CONDITION_SCORE,SELLING_PRICE
0,Mercedes-Benz,GLA,2010,193254.0,1.8,Gasoline,Automatic,Sedan,AWD,4.0,5.0,0.0,2.0,Red,40.0,0.0,7.0,39257.66
1,Nissan,Frontier,2021,58800.0,5.7,Gasoline,Automatic,SUV,FWD,4.0,5.0,1.0,3.0,Black,71.0,0.0,2.0,42237.72
2,Hyundai,Palisade,2017,127591.0,2.0,Hybrid,Dual-Clutch,SUV,AWD,5.0,6.0,1.0,1.0,Brown,23.0,0.0,7.0,45240.28
3,BMW,X3,2015,170698.0,2.5,Gasoline,Automatic,Sedan,4WD,4.0,7.0,1.0,2.0,Silver,94.0,0.0,9.0,46287.33
4,Honda,Accord,2022,NaN,1.6,Gasoline,Automatic,SUV,AWD,4.0,5.0,1.0,2.0,Grey,44.0,0.0,6.0,54516.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1810,Volkswagen,Golf,2023,17453.0,6.2,Plug-in Hybrid,CVT,Sedan,FWD,5.0,5.0,0.0,1.0,White,70.0,1.0,8.0,61388.42
1811,Dodge,Charger,2022,52264.0,1.5,Gasoline,Automatic,Hatchback,AWD,5.0,4.0,0.0,1.0,Red,38.0,0.0,7.0,50397.53
1812,Lexus,LS,2023,14516.0,3.5,Gasoline,Automatic,Sedan,AWD,4.0,4.0,0.0,2.0,Brown,76.0,0.0,9.0,75960.00
1813,Nissan,Sentra,2010,211122.0,5.0,Gasoline,Automatic,Truck,FWD,4.0,5.0,0.0,2.0,Green,102.0,1.0,4.0,24357.65
1814,Toyota,RAV4,2015,183760.0,3.0,Gasoline,Automatic,Sedan,4WD,5.0,5.0,0.0,1.0,Red,70.0,0.0,9.0,37921.61

In [43]:
display(df['MAKE'].hasnans)

False

In [44]:
print(df.columns[df.isna().any()])

Index(['KILOMETRES', 'ENGINE_SIZE', 'FUEL_TYPE', 'TRANSMISSION', 'BODY_TYPE',
       'DRIVETRAIN', 'DOORS', 'SEATS', 'ACCIDENTS', 'OWNERS', 'COLOUR',
       'LISTING_DAYS', 'HAS_WARRANTY', 'CONDITION_SCORE', 'SELLING_PRICE'],
      dtype='object')

In [45]:
display(vehicle_dataset.isna().sum())

MAKE                0
MODEL               0
YEAR                0
KILOMETRES         36
ENGINE_SIZE        54
FUEL_TYPE          19
TRANSMISSION       27
BODY_TYPE          18
DRIVETRAIN         45
DOORS              18
SEATS              18
ACCIDENTS          36
OWNERS             37
COLOUR             54
LISTING_DAYS       18
HAS_WARRANTY       27
CONDITION_SCORE    37
SELLING_PRICE      10
dtype: int64

In [46]:
df[df.isna().any(axis=1)]

,MAKE,MODEL,YEAR,KILOMETRES,ENGINE_SIZE,FUEL_TYPE,TRANSMISSION,BODY_TYPE,DRIVETRAIN,DOORS,SEATS,ACCIDENTS,OWNERS,COLOUR,LISTING_DAYS,HAS_WARRANTY,CONDITION_SCORE,SELLING_PRICE
4,Honda,Accord,2022,NaN,1.6,Gasoline,Automatic,SUV,AWD,4.0,5.0,1.0,2.0,Grey,44.0,0.0,6.0,54516.51
5,Kia,Sorento,2011,174760.0,5.0,Gasoline,Automatic,Sedan,NaN,4.0,4.0,1.0,3.0,Blue,103.0,0.0,9.0,25650.55
8,GMC,Canyon,2014,133487.0,1.6,Gasoline,Dual-Clutch,Sedan,FWD,4.0,NaN,0.0,1.0,Blue,32.0,0.0,5.0,23478.89
9,Jaguar,XF,2018,101490.0,2.0,Gasoline,Automatic,Sedan,FWD,2.0,5.0,3.0,3.0,NaN,40.0,1.0,8.0,42133.82
21,Hyundai,Santa Fe,2022,38703.0,2.0,Gasoline,Manual,NaN,FWD,4.0,5.0,0.0,3.0,White,76.0,1.0,5.0,51659.68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1794,RAM,ProMaster,2020,36824.0,2.4,Gasoline,Automatic,SUV,AWD,4.0,7.0,1.0,2.0,NaN,66.0,1.0,3.0,47472.00
1796,Audi,A4,2010,216523.0,3.6,Gasoline,Automatic,SUV,RWD,4.0,5.0,NaN,3.0,Red,60.0,1.0,7.0,44143.89
1798,Dodge,Charger,2017,105760.0,NaN,Diesel,Automatic,Sedan,FWD,4.0,5.0,2.0,2.0,Blue,113.0,1.0,10.0,39016.51
1799,Mercedes-Benz,S-Class,2011,189710.0,2.5,Gasoline,Automatic,Wagon,AWD,5.0,5.0,0.0,NaN,Blue,63.0,0.0,9.0,38523.19
1801,Hyundai,Sonata,2020,75686.0,1.8,Gasoline,Automatic,Sedan,FWD,4.0,5.0,2.0,3.0,White,NaN,0.0,9.0,40254.07

In [47]:
# Make a copy of the dataframe
df_cleaned = df.copy()

# Identify numerical and categorical columns
num_cols = df_cleaned.select_dtypes(include=['float64', 'int64']).columns
cat_cols = df_cleaned.select_dtypes(include=['object', 'category']).columns

# Impute numerical columns with their median
for col in num_cols:
    if df_cleaned[col].isnull().any():
        median_val = df_cleaned[col].median()
        df_cleaned[col] = df_cleaned[col].fillna(median_val)

# Impute categorical columns with their mode
for col in cat_cols:
    if df_cleaned[col].isnull().any():
        mode_val = df_cleaned[col].mode()[0]
        df_cleaned[col] = df_cleaned[col].fillna(mode_val)

# Verify that there are no remaining missing values
print("Remaining missing values:")
print(df_cleaned.isnull().sum())

Remaining missing values:
MAKE               0
MODEL              0
YEAR               0
KILOMETRES         0
ENGINE_SIZE        0
FUEL_TYPE          0
TRANSMISSION       0
BODY_TYPE          0
DRIVETRAIN         0
DOORS              0
SEATS              0
ACCIDENTS          0
OWNERS             0
COLOUR             0
LISTING_DAYS       0
HAS_WARRANTY       0
CONDITION_SCORE    0
SELLING_PRICE      0
dtype: int64

In [48]:
display(df_cleaned)

,MAKE,MODEL,YEAR,KILOMETRES,ENGINE_SIZE,FUEL_TYPE,TRANSMISSION,BODY_TYPE,DRIVETRAIN,DOORS,SEATS,ACCIDENTS,OWNERS,COLOUR,LISTING_DAYS,HAS_WARRANTY,CONDITION_SCORE,SELLING_PRICE
0,Mercedes-Benz,GLA,2010,193254.0,1.8,Gasoline,Automatic,Sedan,AWD,4.0,5.0,0.0,2.0,Red,40.0,0.0,7.0,39257.66
1,Nissan,Frontier,2021,58800.0,5.7,Gasoline,Automatic,SUV,FWD,4.0,5.0,1.0,3.0,Black,71.0,0.0,2.0,42237.72
2,Hyundai,Palisade,2017,127591.0,2.0,Hybrid,Dual-Clutch,SUV,AWD,5.0,6.0,1.0,1.0,Brown,23.0,0.0,7.0,45240.28
3,BMW,X3,2015,170698.0,2.5,Gasoline,Automatic,Sedan,4WD,4.0,7.0,1.0,2.0,Silver,94.0,0.0,9.0,46287.33
4,Honda,Accord,2022,121216.0,1.6,Gasoline,Automatic,SUV,AWD,4.0,5.0,1.0,2.0,Grey,44.0,0.0,6.0,54516.51
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1810,Volkswagen,Golf,2023,17453.0,6.2,Plug-in Hybrid,CVT,Sedan,FWD,5.0,5.0,0.0,1.0,White,70.0,1.0,8.0,61388.42
1811,Dodge,Charger,2022,52264.0,1.5,Gasoline,Automatic,Hatchback,AWD,5.0,4.0,0.0,1.0,Red,38.0,0.0,7.0,50397.53
1812,Lexus,LS,2023,14516.0,3.5,Gasoline,Automatic,Sedan,AWD,4.0,4.0,0.0,2.0,Brown,76.0,0.0,9.0,75960.00
1813,Nissan,Sentra,2010,211122.0,5.0,Gasoline,Automatic,Truck,FWD,4.0,5.0,0.0,2.0,Green,102.0,1.0,4.0,24357.65
1814,Toyota,RAV4,2015,183760.0,3.0,Gasoline,Automatic,Sedan,4WD,5.0,5.0,0.0,1.0,Red,70.0,0.0,9.0,37921.61

In [49]:
df.to_excel('output.xlsx',index=False)